#ifndef MINITOR_CONFIG_H
#define MINITOR_CONFIG_H

#define DEBUG_MINITOR
#define MINITOR_RELAY_MAX 60
#define MINITOR_CHUTNEY
#define MINITOR_CHUTNEY_ADDRESS 0x1001a8c0
// #define MINITOR_CHUTNEY_ADDRESS 0x8a01a8c0

#endif
