#ifndef MINITOR_CONSTANTS
#define MINITOR_TAG "MINITOR"

#define H_LENGTH 32
#define ID_LENGTH 20
#define G_LENGTH 32
#define DIGEST_LEN 20

#define HSDIR_INTERVAL_DEFAULT 1440
#define HSDIR_N_REPLICAS_DEFAULT 2
#define HSDIR_SPREAD_STORE_DEFAULT 4

#define MINITOR_CONSTANTS
#endif
